### ISSUE TITLE
Typo in Table Viewer Documentation 

### ISSUE THREAD

**Issue by jakobrehmann** [simwrapper/simwrapper.github.io#3]
@frievoe97 Thank you very much for updating the table viewer and adding the docs last week. I found two small errors in the documentation file: 
- The very last configuration option should be showAll**R**ows not showAllrows .
- There is a section title called "Pie Chart Properties" which is probably a copy and paste error. 

https://github.com/simwrapper/simwrapper.github.io/blob/main/docs/ref-table.md

**Comment by frievoe97** [comment]
Thanks for noticing this :) This should now be correct!
